name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: petfinderapi
        
      redis:
          image: redis:alpine
          ports:
            - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run test:e2e
        env:
          JWT_SECRET: petfinderapi
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/petfinderapi?schema=public"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: petfinder-s3
          AWS_REGION: ${{ secrets.AWS_REGION }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          SENTRY_DNS: ${{ secrets.SENTRY_DNS }}